automation:

#############################
# LIGHT SWITCH IS AUTOMATED #
#############################

- id: 62ab2255-a7f8-4243-b53e-341d6998cba1
  alias: carls office - light switch is automated
  max_exceeded: silent
  trigger:

  # main light button pressed
  - platform: event
    event_type: zwave_js_value_notification
    event_data:
      node_id: 94
      property_name: scene
      property_key_name: '002'
      value: KeyPressed
    id: main-light-button-pressed

  # side light button top tapped once
  - platform: event
    event_type: zwave_js_value_notification
    event_data:
      node_id: 94
      property_name: scene
      property_key_name: '003'
      value: KeyPressed
    id: side-light-button-top-tapped-once

  # side light button bottom tapped once
  - platform: event
    event_type: zwave_js_value_notification
    event_data:
      node_id: 94
      property_name: scene
      property_key_name: '004'
      value: KeyPressed
    id: side-light-button-bottom-tapped-once

  # main fan button pressed
  - platform: event
    event_type: zwave_js_value_notification
    event_data:
      node_id: 94
      property_name: scene
      property_key_name: '001'
      value: KeyPressed
    id: main-fan-button-pressed

  # side fan button top tapped once
  - platform: event
    event_type: zwave_js_value_notification
    event_data:
      node_id: 94
      property_name: scene
      property_key_name: '005'
      value: KeyPressed
    id: side-fan-button-top-tapped-once

  # side fan button bottom tapped once
  - platform: event
    event_type: zwave_js_value_notification
    event_data:
      node_id: 94
      property_name: scene
      property_key_name: '006'
      value: KeyPressed
    id: side-fan-button-bottom-tapped-once

  action:
  - choose:

    # main light button pressed (fan light off)
    - conditions:
      - condition: trigger
        id: main-light-button-pressed
      - condition: state
        entity_id: light.office_switch
        state: 'off'
      sequence:
      - service: light.turn_on
        target:
          entity_id: light.office_switch
        data:
          brightness_pct: 100

    # main light button pressed (fan light on)
    - conditions:
      - condition: trigger
        id: main-light-button-pressed
      - condition: state
        entity_id: light.office_switch
        state: 'on'
      sequence:
      - service: light.turn_off
        target:
          entity_id: light.office_switch

    # side light button top tapped once
    - conditions:
      - condition: trigger
        id: side-light-button-top-tapped-once
      sequence:
      - service: light.turn_on
        entity_id: light.office_switch
        data_template:
          brightness: >-
            {% set maximum = 255 %}
            {% set percentStep = 25 %}

            {% set brightness = 0 %}
            {% if ('brightness' in states.light.office_switch.attributes) and (states.light.office_switch.attributes.brightness != None) %}
              {% set brightness = states.light.office_switch.attributes.brightness %}
            {% endif %}

            {% set percent = (((brightness / maximum) * 100) + percentStep) %}
            {% if (percent > 100) %}
              {% set percent = 100 %}
            {% endif %}

            {{ ((percent / 100) * maximum) }}

    # side light button bottom tapped once
    - conditions:
      - condition: trigger
        id: side-light-button-bottom-tapped-once
      sequence:
      - service: light.turn_on
        entity_id: light.office_switch
        data_template:
          brightness: >-
            {% set maximum = 255 %}
            {% set percentStep = 25 %}

            {% set brightness = 0 %}
            {% if ('brightness' in states.light.office_switch.attributes) and (states.light.office_switch.attributes.brightness != None) %}
              {% set brightness = states.light.office_switch.attributes.brightness %}
            {% endif %}

            {% set percent = (((brightness / maximum) * 100) - percentStep) %}
            {% if (percent < 0) %}
              {% set percent = 0 %}
            {% endif %}

            {{ ((percent / 100) * maximum) }}

    # main fan button pressed (fan off)
    - conditions:
      - condition: trigger
        id: main-fan-button-pressed
      - condition: state
        entity_id: fan.office_switch
        state: 'off'
      sequence:
      - service: fan.turn_on
        target:
          entity_id: fan.office_switch
        data:
          percentage: 100

    # main fan button pressed (fan on)
    - conditions:
      - condition: trigger
        id: main-fan-button-pressed
      - condition: state
        entity_id: fan.office_switch
        state: 'on'
      sequence:
      - service: fan.turn_off
        target:
          entity_id: fan.office_switch

    # side fan button top tapped once
    - conditions:
      - condition: trigger
        id: side-fan-button-top-tapped-once
      sequence:
      - service: fan.turn_on
        target:
          entity_id: fan.office_switch
        data_template:
          percentage: >-
            {% set percent = 0 %}
            {% if 'percentage' in states.fan.office_switch.attributes %}
              {% set percent = states.fan.office_switch.attributes.percentage %}
            {% endif %}

            {% set step = 16.67 %}
            {% if 'percentage_step' in states.fan.office_fan.attributes %}
              {% set step = states.fan.office_fan.attributes.percentage_step %}
            {% endif %}

            {% set percent = percent + step %}
            {% if (percent > 100) %}
              {% set percent = 100 %}
            {% endif %}

            {{ percent }}

    # side fan button bottom tapped once
    - conditions:
      - condition: trigger
        id: side-fan-button-bottom-tapped-once
      sequence:
      - service: fan.turn_on
        target:
          entity_id: fan.office_switch
        data_template:
          percentage: >-
            {% set percent = 0 %}
            {% if 'percentage' in states.fan.office_switch.attributes %}
              {% set percent = states.fan.office_switch.attributes.percentage %}
            {% endif %}

            {% set step = 16.67 %}
            {% if 'percentage_step' in states.fan.office_fan.attributes %}
              {% set step = states.fan.office_fan.attributes.percentage_step %}
            {% endif %}

            {% set percent = percent - step %}
            {% if (percent < 0) %}
              {% set percent = 0 %}
            {% endif %}

            {{ percent }}

####################################
# FAN & LIGHT AUTOMATICALLY TOGGLE #
####################################

- id: 4f72b9b1-3039-4bcd-b313-ae962d805365
  alias: carls office - fan and light automatically toggle
  trigger:

  # fan light switch changed state
  - platform: state
    entity_id: light.office_switch
    id: fan-light-switch-changed-state

  # fan switch changed state
  - platform: state
    entity_id: fan.office_switch
    id: fan-switch-changed-state

  action:
  - choose:

    # fan light switch changed state
    - conditions:
      - condition: trigger
        id: fan-light-switch-changed-state
      sequence:
      - service: light.turn_on
        target:
          entity_id: light.office_fan
        data_template:
          brightness: >-
            {% set brightness = 0 %}
            {% if ('brightness' in states.light.office_switch.attributes) and (states.light.office_switch.attributes.brightness != None) %}
              {% set brightness = states.light.office_switch.attributes.brightness %}
            {% endif %}

            {{ brightness }}

    # fan switch changed state
    - conditions:
      - condition: trigger
        id: fan-switch-changed-state
      sequence:
      - service: fan.turn_on
        target:
          entity_id: fan.office_fan
        data_template:
          percentage: >-
            {% set percentage = 0 %}
            {% if 'percentage' in states.fan.office_switch.attributes %}
              {% set percentage = states.fan.office_switch.attributes.percentage %}
            {% endif %}

            {{ percentage }}

#####################
# CUBE CONTROLS FAN #
#####################

- id: 1b100a62-eb6a-4e1a-af70-11d3eaef2262
  alias: carls office - cube controls fan
  trigger:

  # tap
  - platform: mqtt
    topic: "zigbee2mqtt/Carls Office Cube/action"
    payload: "tap"
    id: tap

  action:
  - choose:

    # tap on side 1 toggles fan
    - conditions:
      - condition: state
        entity_id: sensor.carls_office_cube_side
        state: '1'
      - condition: trigger
        id: tap
      sequence:
      - service: fan.toggle
        target:
          entity_id: fan.office_switch

#######################
# CUBE CONTROLS LIGHT #
#######################

- id: b4758783-f9ad-4e57-bbe1-2fa97f0a6803
  alias: carls office - cube controls light
  max_exceeded: silent
  trigger:

  # tap
  - platform: mqtt
    topic: "zigbee2mqtt/Carls Office Cube/action"
    payload: "tap"
    id: tap

  # rotate-left
  - platform: mqtt
    topic: "zigbee2mqtt/Carls Office Cube/action"
    payload: "rotate_left"
    id: rotate-left

  # rotate-right
  - platform: mqtt
    topic: "zigbee2mqtt/Carls Office Cube/action"
    payload: "rotate_right"
    id: rotate-right

  action:
  - choose:

    # tap on side 0 turns fan light on
    - conditions:
      - condition: state
        entity_id: sensor.carls_office_cube_side
        state: '0'
      - condition: trigger
        id: tap
      - condition: state
        entity_id: light.office_switch
        state: 'off'
      sequence:
      - service: light.turn_on
        target:
          entity_id: light.office_switch
        data:
          brightness_pct: 100

    # tap on side 0 turns fan light off
    - conditions:
      - condition: state
        entity_id: sensor.carls_office_cube_side
        state: '0'
      - condition: trigger
        id: tap
      - condition: state
        entity_id: light.office_switch
        state: 'on'
      sequence:
      - service: light.turn_off
        target:
          entity_id: light.office_switch

    # rotate-left on side 0 decreases fan light brightness
    - conditions:
      - condition: state
        entity_id: sensor.carls_office_cube_side
        state: '0'
      - condition: trigger
        id: rotate-left
      sequence:
      - service: light.turn_on
        target:
          entity_id: light.office_switch
        data:
          brightness_pct: >-
            {% set brightness = state_attr('light.office_switch', 'brightness') %}
            {% set step = 25 %}
            {% if not brightness %}
              0
            {% else %}
              {% set percent = (((brightness | int) / 255) * 100) - step %}
              {% if percent < 0 %}
                0
              {% else %}
                {{ percent }}
              {% endif %}
            {% endif %}

    # rotate-right on side 0 increases fan light brightness
    - conditions:
      - condition: state
        entity_id: sensor.carls_office_cube_side
        state: '0'
      - condition: trigger
        id: rotate-right
      sequence:
      - service: light.turn_on
        target:
          entity_id: light.office_switch
        data:
          brightness_pct: >-
            {% set brightness = state_attr('light.office_switch', 'brightness') %}
            {% set step = 25 %}
            {% if not brightness %}
              25
            {% else %}
              {% set percent = (((brightness | int) / 255) * 100) + step %}
              {% if percent > 100 %}
                100
              {% else %}
                {{ percent }}
              {% endif %}
            {% endif %}

#######################
# CUBE CONTROLS SONOS #
#######################

- id: 9af3c747-c0d6-4f08-8f46-215661c0db18
  alias: carls office - cube controls sonos
  trigger:

  # tap
  - platform: mqtt
    topic: "zigbee2mqtt/Carls Office Cube/action"
    payload: "tap"
    id: tap

  # action-angle
  - platform: state
    entity_id: sensor.carls_office_cube_action_angle
    id: action-angle

  action:
  - choose:

    # tap toggles sonos
    - conditions:
      - condition: trigger
        id: tap
      - condition: state
        entity_id: sensor.carls_office_cube_side
        state: '2'
      sequence:
      - service: media_player.media_play_pause
        target:
          entity_id: media_player.office

    # action-angle
    - conditions:
      - condition: trigger
        id: action-angle
      - condition: state
        entity_id: sensor.carls_office_cube_side
        state: '2'
      sequence:
      - service: media_player.volume_set
        target:
          entity_id: media_player.office
        data:
          volume_level: >
            {% set stepSize = (trigger.to_state.state | float(1) ) * 0.05 %}
            {% set volume = (state_attr('media_player.office', 'volume_level') | float(10)) * 100.00 %}
            {% set newVolume = (volume | int(10)) + stepSize %}

            {% if newVolume <= 0.00 %}
              0.00
            {% elif newVolume >= 100 %}
              1.00
            {% else %}
              {{ newVolume / 100 }}
            {% endif %}
