group:

  lights_great_room:
    name: All Great Room Lights
    entities:
    - light.great_room_fan
    - light.great_room_lights_switch
    - light.entertainment_center_left_bottom_1
    - light.entertainment_center_left_bottom_2
    - light.entertainment_center_left_bottom_3
    - light.entertainment_center_left_bottom_4
    - light.entertainment_center_right_bottom_1
    - light.entertainment_center_right_bottom_2
    - light.entertainment_center_right_bottom_3
    - light.entertainment_center_right_bottom_4

  lights_entertainment_center_all:
    name: All Entertainment Center Lights
    entities:
    - light.entertainment_center_left_bottom_1
    - light.entertainment_center_left_bottom_2
    - light.entertainment_center_left_bottom_3
    - light.entertainment_center_left_bottom_4
    - light.entertainment_center_right_bottom_1
    - light.entertainment_center_right_bottom_2
    - light.entertainment_center_right_bottom_3
    - light.entertainment_center_right_bottom_4

  lights_entertainment_center_left_side:
    name: All Entertainment Center Lights - Left Side
    entities:
    - light.entertainment_center_left_bottom_1
    - light.entertainment_center_left_bottom_2
    - light.entertainment_center_left_bottom_3
    - light.entertainment_center_left_bottom_4

  lights_entertainment_center_right_side:
    name: All Entertainment Center Lights - Right Side
    entities:
    - light.entertainment_center_right_bottom_1
    - light.entertainment_center_right_bottom_2
    - light.entertainment_center_right_bottom_3
    - light.entertainment_center_right_bottom_4

  lights_entertainment_center_alt_one:
    name: Entertainment Center Alt One
    entities:
    - light.entertainment_center_left_bottom_4
    - light.entertainment_center_left_bottom_2
    - light.entertainment_center_right_bottom_3
    - light.entertainment_center_right_bottom_1

  lights_entertainment_center_alt_two:
    name: Entertainment Center Alt Two
    entities:
    - light.entertainment_center_left_bottom_3
    - light.entertainment_center_left_bottom_1
    - light.entertainment_center_right_bottom_4
    - light.entertainment_center_right_bottom_2

homeassistant:
  customize:

    light.great_room_lights_switch:
      friendly_name: Great Room Ceiling Lights

    sensor.arcana_power_switch:
      friendly_name: Arcana Power Switch

automation:

#############################
# LIGHT SWITCH IS AUTOMATED #
#############################

- id: c2a90257-f99f-432b-af81-4dec906e1483
  alias: great room - light switch is automated
  trigger:

  # two taps up
  - platform: event
    event_type: zwave_js_value_notification
    event_data:
      node_id: 96
      property_name: scene
      property_key_name: '002'
      value: KeyPressed2x
    id: two-taps-up

  # two taps down
  - platform: event
    event_type: zwave_js_value_notification
    event_data:
      node_id: 96
      property_name: scene
      property_key_name: '001'
      value: KeyPressed2x
    id: two-taps-down

  action:
  - choose:

    # two taps up
    - conditions:
      - condition: trigger
        id: two-taps-up
      sequence:
      - service: fan.turn_on
        target:
          entity_id: fan.great_room_fan
        data:
          percentage: 100

    # two taps down
    - conditions:
      - condition: trigger
        id: two-taps-down
      sequence:
      - service: fan.turn_off
        target:
          entity_id: fan.great_room_fan

#############################################
# ENTERTAINMENT CENTER LIGHTS ARE AUTOMATED #
#############################################

- id: 90241217-af72-4b3e-8264-d3561627ba5d
  alias: great room - entertainment center lights are automated
  trigger:

  # auto on time
  - platform: sun
    event: sunset
    offset: "-00:30:00"
    id: auto-on-time

  # auto off time
  - platform: time
    at: "00:00:00"
    id: auto-off-time

  action:
  - choose:

    # auto on time
    - conditions:
      - condition: trigger
        id: auto-on-time
      sequence:
      - service: light.turn_on
        target:
          entity_id: group.lights_entertainment_center_all
        data:
          brightness_pct: 100
      - service: script.fireplace_toggle_power

    # auto off time
    - conditions:
      - condition: trigger
        id: auto-off-time
      sequence:
      - service: light.turn_off
        target:
          entity_id: group.lights_entertainment_center_all
      - service: script.fireplace_toggle_power

#######################################
# CHRISTMAS TREE LIGHTS ARE AUTOMATED #
#######################################

- id: e9afbf45-5eed-4869-b2f3-a0cf56b23a00
  alias: great room - christmas tree lights are automated
  trigger:

  # auto on time
  - platform: sun
    event: sunset
    offset: "-00:30:00"
    id: auto-on-time

  # auto off time
  - platform: time
    at: "00:00:00"
    id: auto-off-time

  action:
  - choose:

    # auto on time
    - conditions:
      - condition: trigger
        id: auto-on-time
      sequence:
      - service: light.turn_on
        target:
          entity_id: light.christmas_tree
        data:
          brightness_pct: 100

    # auto off time
    - conditions:
      - condition: trigger
        id: auto-off-time
      sequence:
      - service: light.turn_off
        target:
          entity_id: light.christmas_tree
