group:

  lights_guest_bathroom:
    name: All Guest Bathroom Lights
    entities:
    - light.guest_bathroom_vanity_switch

homeassistant:
  customize:

    light.guest_bathroom_vanity_switch:
      friendly_name: Guest Bathroom Vanity Switch

automation:

######################################
# VANITY LIGHTS AUTOMATICALLY TOGGLE #
######################################

- id: a488c2b4-213f-4f93-8feb-be9c9c43eedc
  alias: guest bathroom - vanity lights automatically toggle
  trigger:

  # motion detected
  - platform: state
    entity_id: binary_sensor.guest_bathroom_motion_sensor_occupancy
    from: 'off'
    to: 'on'
    id: detected-motion

  # no more motion
  - platform: state
    entity_id: binary_sensor.guest_bathroom_motion_sensor_occupancy
    from: 'on'
    to: 'off'
    for:
      minutes: 5
    id: no-more-motion

  action:
  - choose:

    # motion detected (during the day)
    - conditions:
      - condition: trigger
        id: detected-motion
      - condition: and
        conditions:
        - condition: sun
          after: sunrise
          after_offset: '00:30:00'
        - condition: sun
          before: sunset
          before_offset: '-00:30:00'
      sequence:
      - service: light.turn_on
        target:
          entity_id: light.guest_bathroom_vanity_switch
        data:
          brightness_pct: 100

    # motion detected (during the night)
    - conditions:
      - condition: trigger
        id: detected-motion
      - condition: or
        conditions:
        - condition: sun
          after: sunset
          after_offset: '-00:30:00'
        - condition: sun
          before: sunrise
          before_offset: '00:30:00'
      sequence:
      - service: light.turn_on
        target:
          entity_id: light.guest_bathroom_vanity_switch
        data:
          brightness_pct: 50

    # no more motion
    - conditions:
      - condition: trigger
        id: no-more-motion
      sequence:
      - service: light.turn_off
        target:
          entity_id: light.guest_bathroom_vanity_switch

###########################
# HELP BUTTON PLAYS SOUND #
###########################

- id: 2d531108-c11b-402e-8cec-105455b3d2fa
  alias: guest bathroom - help button plays sound
  trigger:

  - trigger: mqtt
    topic: "zigbee2mqtt/Guest Bathroom Help Button/action"
    payload: "single"
    id: single-tap

  action:

  - conditions:
    - condition: trigger
      id: single-tap
    sequence:
    - service: script.sonos_cloud_play_local_sound
      data_template:
        speakers: >-
          {% set speakers = "'media_player.great_room_cloud'" %}
          {% set speakers = speakers + ", 'media_player.office_cloud'" %}
          {% set speakers = speakers + ", 'media_player.roam_cloud'" %}
          {% set speakers = speakers + ", 'media_player.master_bedroom_cloud'" %}

          {% set speakers = '[' + speakers + ']' %}
          {{ speakers }}
        file: help-guest-bathroom.mp3
        volume: 80
