group:

  lights_sadies_room:
    name: All Sadie's Room Lights
    entities:
    - light.sadies_room_main_switch

automation:

#############################
# LIGHT SWITCH IS AUTOMATED #
#############################

- id: e9eee803-63a3-44ca-aa7d-02d08532a89d
  alias: sadies room - light switch is automated
  trigger:

  # main light button pressed
  - platform: event
    event_type: zwave_js_value_notification
    event_data:
      node_id: 80
      property_name: scene
      property_key_name: '002'
      value: KeyPressed
    id: main-light-button-pressed

  # side light button top tapped once
  - platform: event
    event_type: zwave_js_value_notification
    event_data:
      node_id: 80
      property_name: scene
      property_key_name: '003'
      value: KeyPressed
    id: side-light-button-top-tapped-once

  # side light button bottom tapped once
  - platform: event
    event_type: zwave_js_value_notification
    event_data:
      node_id: 80
      property_name: scene
      property_key_name: '004'
      value: KeyPressed
    id: side-light-button-bottom-tapped-once

  # main fan button pressed
  - platform: event
    event_type: zwave_js_value_notification
    event_data:
      node_id: 80
      property_name: scene
      property_key_name: '001'
      value: KeyPressed
    id: main-fan-button-pressed

  # side fan button top tapped once
  - platform: event
    event_type: zwave_js_value_notification
    event_data:
      node_id: 80
      property_name: scene
      property_key_name: '005'
      value: KeyPressed
    id: side-fan-button-top-tapped-once

  # side fan button bottom tapped once
  - platform: event
    event_type: zwave_js_value_notification
    event_data:
      node_id: 80
      property_name: scene
      property_key_name: '006'
      value: KeyPressed
    id: side-fan-button-bottom-tapped-once

  action:
  - choose:

    # main light button pressed (fan light off)
    - conditions:
      - condition: trigger
        id: main-light-button-pressed
      - condition: state
        entity_id: light.sadies_room_main_switch
        state: 'off'
      sequence:
      - service: light.turn_on
        target:
          entity_id: light.sadies_room_main_switch
        data:
          brightness_pct: 100

    # main light button pressed (fan light on)
    - conditions:
      - condition: trigger
        id: main-light-button-pressed
      - condition: state
        entity_id: light.sadies_room_main_switch
        state: 'on'
      sequence:
      - service: light.turn_off
        target:
          entity_id: light.sadies_room_main_switch

    # side light button top tapped once
    - conditions:
      - condition: trigger
        id: side-light-button-top-tapped-once
      sequence:
      - service: light.turn_on
        entity_id: light.sadies_room_main_switch
        data_template:
          brightness: >-
            {% set maximum = 255 %}
            {% set percentStep = 25 %}

            {% set brightness = 0 %}
            {% if ('brightness' in states.light.sadies_room_main_switch.attributes) and (states.light.sadies_room_main_switch.attributes.brightness != None) %}
              {% set brightness = states.light.sadies_room_main_switch.attributes.brightness %}
            {% endif %}

            {% set percent = (((brightness / maximum) * 100) + percentStep) %}
            {% if (percent > 100) %}
              {% set percent = 100 %}
            {% endif %}

            {{ ((percent / 100) * maximum) }}

    # side light button bottom tapped once
    - conditions:
      - condition: trigger
        id: side-light-button-bottom-tapped-once
      sequence:
      - service: light.turn_on
        entity_id: light.sadies_room_main_switch
        data_template:
          brightness: >-
            {% set maximum = 255 %}
            {% set percentStep = 25 %}

            {% set brightness = 0 %}
            {% if ('brightness' in states.light.sadies_room_main_switch.attributes) and (states.light.sadies_room_main_switch.attributes.brightness != None) %}
              {% set brightness = states.light.sadies_room_main_switch.attributes.brightness %}
            {% endif %}

            {% set percent = (((brightness / maximum) * 100) - percentStep) %}
            {% if (percent < 0) %}
              {% set percent = 0 %}
            {% endif %}

            {{ ((percent / 100) * maximum) }}

    # main fan button pressed (fan off)
    - conditions:
      - condition: trigger
        id: main-fan-button-pressed
      - condition: state
        entity_id: fan.sadies_room_main_switch
        state: 'off'
      sequence:
      - service: fan.turn_on
        target:
          entity_id: fan.sadies_room_main_switch
        data:
          percentage: 100

    # main fan button pressed (fan on)
    - conditions:
      - condition: trigger
        id: main-fan-button-pressed
      - condition: state
        entity_id: fan.sadies_room_main_switch
        state: 'on'
      sequence:
      - service: fan.turn_off
        target:
          entity_id: fan.sadies_room_main_switch

    # side fan button top tapped once
    - conditions:
      - condition: trigger
        id: side-fan-button-top-tapped-once
      sequence:
      - service: fan.turn_on
        target:
          entity_id: fan.sadies_room_main_switch
        data_template:
          percentage: >-
            {% set percent = 0 %}
            {% if 'percentage' in states.fan.sadies_room_main_switch.attributes %}
              {% set percent = states.fan.sadies_room_main_switch.attributes.percentage %}
            {% endif %}

            {% set step = 16.67 %}
            {% if 'percentage_step' in states.fan.sadies_room_fan.attributes %}
              {% set step = states.fan.sadies_room_fan.attributes.percentage_step %}
            {% endif %}

            {% set percent = percent + step %}
            {% if (percent > 100) %}
              {% set percent = 100 %}
            {% endif %}

            {{ percent }}

    # side fan button bottom tapped once
    - conditions:
      - condition: trigger
        id: side-fan-button-bottom-tapped-once
      sequence:
      - service: fan.turn_on
        target:
          entity_id: fan.sadies_room_main_switch
        data_template:
          percentage: >-
            {% set percent = 0 %}
            {% if 'percentage' in states.fan.sadies_room_main_switch.attributes %}
              {% set percent = states.fan.sadies_room_main_switch.attributes.percentage %}
            {% endif %}

            {% set step = 16.67 %}
            {% if 'percentage_step' in states.fan.sadies_room_fan.attributes %}
              {% set step = states.fan.sadies_room_fan.attributes.percentage_step %}
            {% endif %}

            {% set percent = percent - step %}
            {% if (percent < 0) %}
              {% set percent = 0 %}
            {% endif %}

            {{ percent }}

######################################
# FAN AND LIGHT AUTOMATICALLY TOGGLE #
######################################

- id: 9e7990a5-41e0-44c9-86e7-d5e6915d61d3
  alias: sadies room - fan and light automatically toggle
  trigger:

  # fan light switch changed state
  - platform: state
    entity_id: light.sadies_room_main_switch
    id: fan-light-switch-changed-state

  # fan switch changed state
  - platform: state
    entity_id: fan.sadies_room_main_switch
    id: fan-switch-changed-state

  action:
  - choose:

    # fan light switch changed state
    - conditions:
      - condition: trigger
        id: fan-light-switch-changed-state
      sequence:
      - service: light.turn_on
        target:
          entity_id: light.sadies_room_fan
        data_template:
          brightness: >-
            {% set brightness = 0 %}
            {% if ('brightness' in states.light.sadies_room_main_switch.attributes) and (states.light.sadies_room_main_switch.attributes.brightness != None) %}
              {% set brightness = states.light.sadies_room_main_switch.attributes.brightness %}
            {% endif %}

            {{ brightness }}

    # fan switch changed state
    - conditions:
      - condition: trigger
        id: fan-switch-changed-state
      sequence:
      - service: fan.turn_on
        target:
          entity_id: fan.sadies_room_fan
        data_template:
          percentage: >-
            {% set percentage = 0 %}
            {% if 'percentage' in states.fan.sadies_room_main_switch.attributes %}
              {% set percentage = states.fan.sadies_room_main_switch.attributes.percentage %}
            {% endif %}

            {{ percentage }}
