automation:

##################################
# OPENING A WINDOW PLAYS A SOUND #
##################################

- id: 116c26da-46a6-4a52-91ee-5727a53f1a39
  alias: windows - opening plays sound
  trigger:
  - platform: state
    entity_id: group.windows_all
    to: 'on'

  action:
  - service: script.sonos_cloud_play_local_sound
    data_template:
      speakers: >-
        {% set speakers = "'media_player.great_room_cloud'" %}
        {% set speakers = speakers + ", 'media_player.office_cloud'" %}
        {% set speakers = speakers + ", 'media_player.roam_cloud'" %}
        {% set speakers = speakers + ", 'media_player.master_bedroom_cloud'" %}

        {% set speakers = '[' + speakers + ']' %}
        {{ speakers }}
      file: window-door-slider-beep.mp3
      volume: 70

##################################
# MOVEMENT TRIGGERS NOTIFICATION #
##################################

- id: b0f2bcd1-ca59-43d4-9315-174230102c1c
  alias: windows - movement triggers notification
  trigger:

  # dining room left
  - platform: state
    entity_id: binary_sensor.dining_room_left_window_contact
    not_from: &notFrom
    - "unknown"
    - "unavailable"
    id: dining-room-left

  # dining room right
  - platform: state
    entity_id: binary_sensor.dining_room_right_window_contact
    not_from: *notFrom
    id: dining-room-right

  # great room left
  - platform: state
    entity_id: binary_sensor.great_room_left_window_contact
    not_from: *notFrom
    id: great-room-left

  # great room right
  - platform: state
    entity_id: binary_sensor.great_room_right_window_contact
    not_from: *notFrom
    id: great-room-right

  # master bedroom left
  - platform: state
    entity_id: binary_sensor.master_bedroom_left_window_contact
    not_from: *notFrom
    id: master-bedroom-left

  # master bedroom right
  - platform: state
    entity_id: binary_sensor.master_bedroom_right_window_contact
    not_from: *notFrom
    id: master-bedroom-right

  # pennys room left
  - platform: state
    entity_id: binary_sensor.pennys_room_left_window_contact
    not_from: *notFrom
    id: pennys-room-left

  # pennys room right
  - platform: state
    entity_id: binary_sensor.pennys_room_right_window_contact
    not_from: *notFrom
    id: pennys-room-right

  # sadies room bathroom
  - platform: state
    entity_id: binary_sensor.sadies_room_bathroom_window_contact
    not_from: *notFrom
    id: sadies-room-bathroom

  # sadies room window
  - platform: state
    entity_id: binary_sensor.sadies_room_window_contact
    not_from: *notFrom
    id: sadies-room-window

  action:
  - choose:

    # dining room left
    - conditions:
      - condition: trigger
        id: dining-room-left
      sequence:
      - service: &notificationScript script.send_window_movement_notification
        data:
          name: Dining Room Left Window
          sensor: binary_sensor.dining_room_left_window_contact

    # dining room right
    - conditions:
      - condition: trigger
        id: dining-room-right
      sequence:
      - service: *notificationScript
        data:
          name: Dining Room Right Window
          sensor: binary_sensor.dining_room_right_window_contact

    # great room left
    - conditions:
      - condition: trigger
        id: great-room-left
      sequence:
      - service: *notificationScript
        data:
          name: Great Room Left Window
          sensor: binary_sensor.great_room_left_window_contact

    # great room right
    - conditions:
      - condition: trigger
        id: great-room-right
      sequence:
      - service: *notificationScript
        data:
          name: Great Room Right Window
          sensor: binary_sensor.great_room_right_window_contact
    
    # master bedroom left
    - conditions:
      - condition: trigger
        id: master-bedroom-left
      sequence:
      - service: *notificationScript
        data:
          name: Master Bedroom Left Window
          sensor: binary_sensor.master_bedroom_left_window_contact

    # master bedroom right
    - conditions:
      - condition: trigger
        id: master-bedroom-right
      sequence:
      - service: *notificationScript
        data:
          name: Master Bedroom Right Window
          sensor: binary_sensor.master_bedroom_right_window_contact

    # pennys room left
    - conditions:
      - condition: trigger
        id: pennys-room-left
      sequence:
      - service: *notificationScript
        data:
          name: Penny's Room Left Window
          sensor: binary_sensor.pennys_room_left_window_contact

    # pennys room right
    - conditions:
      - condition: trigger
        id: pennys-room-right
      sequence:
      - service: *notificationScript
        data:
          name: Penny's Room Right Window
          sensor: binary_sensor.pennys_room_right_window_contact

    # sadies room bathroom
    - conditions:
      - condition: trigger
        id: sadies-room-bathroom
      sequence:
      - service: *notificationScript
        data:
          name: Sadie's Room Bathroom Window
          sensor: binary_sensor.sadies_room_bathroom_window_contact

    # sadies room window
    - conditions:
      - condition: trigger
        id: sadies-room-window
      sequence:
      - service: *notificationScript
        data:
          name: Sadie's Room Window
          sensor: binary_sensor.sadies_room_window_contact


script:

  #####################################
  # SEND WINDOW MOVEMENT NOTIFICATION #
  #####################################

  send_window_movement_notification:
    alias: Send Window Movement Notification
    sequence:
    - service: notify.critical_notification_audience
      data:
        title: >-
          {% if (states(sensor) | lower) == 'on' %}
            ⬆️ Window Opened ⬆️
          {% else %}
            ⬇️ Window Closed ⬇️
          {% endif %}
        message: "{{ name }}"

group:

  windows_all:
    name: All Windows
    entities:
    - binary_sensor.dining_room_left_window_contact
    - binary_sensor.dining_room_right_window_contact
    - binary_sensor.great_room_left_window_contact
    - binary_sensor.great_room_right_window_contact
    - binary_sensor.master_bedroom_left_window_contact
    - binary_sensor.master_bedroom_right_window_contact
    - binary_sensor.pennys_room_left_window_contact
    - binary_sensor.pennys_room_right_window_contact
    - binary_sensor.sadies_room_bathroom_window_contact
    - binary_sensor.sadies_room_window_contact
